services:
  fast-agent-fz:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FAT_ZEBRA_API_URL=${FAT_ZEBRA_API_URL:-https://gateway.sandbox.fatzebra.com.au/v1.0}
      - FAT_ZEBRA_USERNAME=${FAT_ZEBRA_USERNAME:-TEST}
      - FAT_ZEBRA_TOKEN=${FAT_ZEBRA_TOKEN:-TEST}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
