version: '3'

services:
  fast-agent-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7681:7681"
    volumes:
      - ./logs:/app/logs
      - ./fast-agent-fz/fastagent.config.yaml:/app/fastagent.config.yaml
      - ./fast-agent-fz/fastagent.secrets.yaml:/app/fastagent.secrets.yaml
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped