version: "3.8"

services:
  fat-zebra-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7681:7681"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    restart: unless-stopped
    volumes:
      # Optional: Mount a local directory for persistence
      #- ./data:/app/data
      # Optional: Mount AWS credentials from host
      - ~/.aws:/root/.aws:ro
